# Generated by Django 4.2.11 on 2025-05-17 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('findJobApp', '0002_apply_cv_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='followed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('candidate_id', 'employer_id')},
        ),
        migrations.RemoveField(
            model_name='follow',
            name='notify_email',
        ),
    ]
