# Generated by Django 4.2.11 on 2025-05-18 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('findJobApp', '0003_follow_followed_at_alter_follow_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='reviewee_id',
            new_name='reviewee',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='reviewer_id',
            new_name='reviewer',
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('reviewer', 'reviewee', 'job')},
        ),
    ]
