# Generated by Django 4.2.11 on 2025-05-18 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('findJobApp', '0005_candidate_created_at_employer_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification',
            old_name='employer_id',
            new_name='employer',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='document_link',
        ),
        migrations.AddField(
            model_name='verification',
            name='document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='verifications/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
