# Generated by Django 4.2.11 on 2025-06-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findJobApp', '0007_candidate_avatar_employer_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('draft', 'Draft')], default='active', max_length=10),
        ),
    ]
