# Generated by Django 4.2.11 on 2025-06-04 13:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findJobApp', '0008_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
        migrations.AlterUniqueTogether(
            name='apply',
            unique_together={('job_id', 'candidate_id')},
        ),
    ]
